# Generated by Django 5.2 on 2025-06-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_quantity_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sold_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product_instance',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='shop',
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('product_instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='products.productinstance')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
