# Generated by Django 5.2 on 2025-06-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_rfid_remove_product_has_rfid_and_more'),
        ('sales', '0003_refund_refundeditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditem',
            name='product_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productinstance'),
        ),
        migrations.AddIndex(
            model_name='solditem',
            index=models.Index(fields=['product_instance'], name='sales_soldi_product_19a38a_idx'),
        ),
    ]
