# Generated by Django 5.2 on 2025-05-08 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='RFID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop'),
            preserve_default=False,
        ),
    ]
