# Generated by Django 5.2 on 2025-05-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_rfid_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='RFID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
