# Generated by Django 5.2 on 2025-05-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='productinstance',
            index=models.Index(fields=['RFID'], name='products_pr_RFID_90f718_idx'),
        ),
    ]
