# Generated by Django 5.2 on 2025-06-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_rfid',
            field=models.BooleanField(default=False),
        ),
    ]
