# Generated by Django 5.2 on 2025-06-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_has_rfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='RFID',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_rfid',
        ),
        migrations.AddField(
            model_name='product',
            name='rfid_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
